#!/usr/bin/env node
// Regenerates src/generated/* from specs/*.yaml. Equivalent of `make generate` in
// ecosystems-go (which runs oapi-codegen via `go generate ./...`).
//
// Two outputs per run:
//   1. src/generated/<service>.ts  -- openapi-typescript types
//   2. src/generated/servers.ts    -- base URLs read out of each spec's `servers[0].url`
//
// (2) is the equivalent of oapi-codegen's `server-urls: true`. Base URLs come from the
// spec, never from a string retyped in application code.
//
// The generator runs from a throwaway npx install rather than from devDependencies,
// because openapi-typescript emits its output through the TypeScript compiler API
// (`ts.factory`) and typescript@7 -- what this package compiles with -- no longer ships
// one. Both versions below are exact-pinned, so the generated output is reproducible;
// bump them deliberately. This is the npm-shaped equivalent of ecosystems-go keeping
// oapi-codegen in a separate tools/go.mod, minus the second dependency tree.
import { spawnSync } from "node:child_process";
import { readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import YAML from "yaml";

import { SPECS } from "./specs.mjs";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const SPEC_DIR = path.join(ROOT, "specs");
const OUT_DIR = path.join(ROOT, "src", "generated");

const GENERATOR = "openapi-typescript@7.13.0";
/** openapi-typescript's peer. Must stay on 5.x; see the note above. */
const GENERATOR_TYPESCRIPT = "typescript@5.9.3";

/** npx must go through a shell on Windows, which does not quote arguments for us. */
const quote = (arg) => (/\s/.test(arg) ? `"${arg}"` : arg);

function generateTypes(spec) {
  const input = path.join(SPEC_DIR, `${spec.name}.yaml`);
  const output = path.join(OUT_DIR, `${spec.name}.ts`);
  const args = [
    "--yes",
    "-p",
    GENERATOR,
    "-p",
    GENERATOR_TYPESCRIPT,
    "openapi-typescript",
    input,
    "-o",
    output,
  ];
  const result = spawnSync("npx", args.map(quote), { stdio: "inherit", shell: true });
  if (result.status !== 0) {
    throw new Error(`openapi-typescript failed for ${spec.name} (exit ${result.status})`);
  }
}

async function readServerURL(spec) {
  const doc = YAML.parse(await readFile(path.join(SPEC_DIR, `${spec.name}.yaml`), "utf8"));
  const url = doc?.servers?.[0]?.url;
  if (typeof url !== "string" || url.length === 0) {
    throw new Error(`${spec.name}.yaml has no servers[0].url`);
  }
  return url.replace(/\/+$/, "");
}

async function writeServers(entries) {
  const lines = [
    "// Code generated by scripts/generate.mjs. DO NOT EDIT.",
    "// Base URLs are read from each spec's `servers[0].url`.",
    "",
    "export const DEFAULT_SERVERS = {",
    ...entries.map(([name, url]) => `  ${name}: ${JSON.stringify(url)},`),
    "} as const;",
    "",
    "export type ServiceName = keyof typeof DEFAULT_SERVERS;",
    "",
  ];
  await writeFile(path.join(OUT_DIR, "servers.ts"), lines.join("\n"), "utf8");
}

async function main() {
  const entries = [];
  for (const spec of SPECS) {
    console.log(`generating ${spec.name} ...`);
    generateTypes(spec);
    entries.push([spec.name, await readServerURL(spec)]);
  }
  await writeServers(entries);
  console.log("\ngenerated:");
  for (const [name, url] of entries) console.log(`  ${name.padEnd(11)} ${url}`);
}

await main();
